#!/usr/bin/env bash

. ./dl.sh

[ "$(nproc)" -eq 1 ] &&
	skip 'need multi processor'

create_script <<-EOF
dl fetcher sleeper sleep
for i in \$(seq "$(nproc)")
do
	dl add -f sleeper -o out\$i 1
done
EOF

out=$(command time -f '%e' dl 2>&1 >2 | tail -n1 | cut -d . -f 1)

for i in $(seq "$(nproc)")
do
	[ -e out$i ]
done

[ "$out" -lt "$(nproc)" ] ||
	fail 'not faster than single thread'
