#!/usr/bin/env bash

. ./dl.sh

dl extension &&
	fail 'extension should not already exist' || :

mkdir subdir
ln -s /bin/echo subdir/dl-extension
export PATH="$PATH:$PWD/subdir"

output=$(dl extension can have args ||
	fail 'extension should exist')
[ "$output" = 'can have args' ] ||
	fail 'extension should pass args'
