#!/usr/bin/env bash

. ./dl.sh

[ "$(nproc)" -eq 1 ] &&
	skip 'need multi processor'

create_script a b c d <<-EOF
dl fetcher sleeper sleep
dl add -f sleeper -o out 1
EOF

out=$(command time -f '%e' dl 2>&1 >2 | tail -n1 | cut -d . -f 1)

[ "$out" -lt "$(nproc)" ] ||
	fail 'not faster than single thread'
