#!/usr/bin/env bash

. ./dl.sh

readonly JOBS=$(($(nproc) * 10))

create_script <<-EOF
for i in \$(seq 40)
do
	( dl fetcher echoer\$i echo &&
	  dl add -f echoer\$i -o echoed\$i \$i ) &
done
for i in \$(seq 40)
do
	wait -n
done
EOF

for _ in $(seq $JOBS)
do
	dl &
done

for _ in $(seq $JOBS)
do
	wait -n
done

for i in $(seq 40)
do
	echo $i | cmp echoed$i
done
